### ISSUE TITLE
No RcppArmadillo needed in Imports

### ISSUE THREAD

**Issue by eddelbuettel** [BerriJ/RcppExtModEx#2]
Apologies for the radio silence, it's been overly busy.  This repo hasn't been forgotten.

One microwart is that RcppArmadillo has to be in LinkingTo (for its headers) as it is, but is not needed in Imports (where we need Rcpp for some run-time initializations that do not apply for RcppArmadillo) and that `R CMD check` complains about.

**Comment by BerriJ** [comment]
Thank you very much. I'm always learning a bit more on how Rcpp works :)

**Comment by eddelbuettel** [comment]
`R CMD check --as-cran` is your friend in that journey.
