### ISSUE TITLE
Missing documentation ?

### ISSUE THREAD

**Issue by eddelbuettel** [BerriJ/RcppExtModEx#3]
The remaining 'wart' from running `R CMD check` (or, as here, via the `rcmdcheck` package) is the documentation:

```
✔  checking Rd line widths ...
✔  checking Rd cross-references ...
W  checking for missing documentation entries ...
   Undocumented code objects:
     ‘getMap’ ‘makeFoo’ ‘mapIn_and_mapOut’ ‘setMap’
   All user-level objects in a package should have documentation entries.
   See chapter ‘Writing R documentation files’ in the ‘Writing R
   Extensions’ manual.
✔  checking for code/documentation mismatches (924ms)
✔  checking Rd \usage sections (721ms)
```

I can probably spend a few minutes on the weekend getting documentation stubs in.  If you beat me to it, even better as you wrote it and may know better what it is doing :)

**Comment by BerriJ** [comment]
Please spend your weekend with something more fun than writing doc stubs. I'll take care of the docs! :+1:

**Comment by BerriJ** [comment]
I documented all functions and also the class. Those functions mainly demonstrate the use of as/wrap and interaction with the Foo class. Therefore I wrote a little bit about what each function demonstrates (and sometimes which Rcpp features are relevant). I used the `@description` field for that. Now as I think about it, we could write those details in `@details`. I'll do that quickly.

**Comment by eddelbuettel** [comment]
Nice, I'll try to catch up.  As it is an 'Ex' package maybe no need to be too exhaustive but I do think clean checks are good (also as a development guideline).

**Comment by BerriJ** [comment]
I think it's in a good state now. I also added an R CMD action. Certainly a bit overkill but it won't hurt.

**Comment by eddelbuettel** [comment]
Indeed that is likely overkill in this copy-and-paste standard use there.  We do not need five runs.  As you are likely aware, you can run `R CMD check` on your machine when you feel like it.  I do that every now and then, and that is how I found what I thought was missing.   I did not suggest we burn all those cpu cycles just because someone made it easy for you to run a usethis or whatever cookie cutter function.  So as you also seem to think it is overkill, maybe it is better to edit it down or nuke it entirely.

**Comment by BerriJ** [comment]
I agree. I edited the `.yml` so that the checks only run when PR's are opened. This way we get automated checks but rely on local checks as long as we push directly (which we probably do most of the time). I also removed the ubuntu old-rel and ubuntu devel platform checks.
